### ISSUE TITLE
why a varargs/overloaded API?

### ISSUE THREAD

**Issue by leeoniya** [Riim/cellx#37]
hey @Riim,

why this

```js
user.fullName('subscribe', function() {
    console.log('fullName: ' + this.fullName());
});
```

instead of this?

```js
user.fullName.subscribe(function() {
    console.log('fullName: ' + this.fullName());
})
```

there could be better benefits for API discoverability, minification and performance by using separate instance methods instead of overloading the getter/setter functionality and relying on arg count.

what do you think?

**Comment by Riim** [comment]
Hi,
done in `v1.9.0`

Previously, there were problems with it due to the impossibility of installing a prototype for functions:
```js
let fn = function() {};
Object.setPrototypeOf(fn, {
    __proto__: Function.prototype,
    // ...
})
```
Rewrite a lot methods in the loop is not suitable, because it is slow:
```js
let fn = function() {};
for (let name in methods) {
    fn[name] = methods[name];
}
```

Now, no problem. Also now possible to use with decorators: [cellx-decorators](https://github.com/Riim/cellx-decorators).

**Comment by leeoniya** [comment]
great, thanks!
